import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="text-white bg-gradient-to-r from-indigo-700 via-violet-700 to-orange-700 top-0 z-50 sticky">
          <Header />
        </header>
        {children}
        <footer className="container">
          <Footer />
        </footer>
      </body>
    </html>
  );
} 
